name: Build & Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-test:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    container:
      image: hexpm/elixir:1.16.0-erlang-26.2.1-alpine-3.17.5
    services:
      ravendb:
        image: ravendb/ravendb
        ports:
          - 8080:8080
        env:
          RAVEN_Setup_Mode: "None"
          RAVEN_License_Eula_Accepted: "true"
          RAVEN_Security_UnsecuredAccessAllowed: "PublicNetwork"
    steps:
      - name: Install Git/Curl/GNU Tar
        run: apk add --no-cache curl tar git make gcc libc-dev g++
      - name: Fix git permissions
        run: git config --global --add safe.directory /__w/ravix-ecto/ravix-ecto
      - uses: actions/checkout@v3
      - name: Install Git client
        run: apk add --no-cache git
      - name: Build & Deps Cache
        uses: actions/cache@v3
        id: mix-deps
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-02-build-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-02-build-${{ hashFiles('mix.lock') }}
            ${{ runner.os }}-02-build-
      # - name: Dyalizer Cache
      #   uses: actions/cache@v3
      #   id: mix-dialyzer
      #   with:
      #     path: priv/plts
      #     key: ${{ runner.os }}-01-dialyzer
      #     restore-keys: |
      #       ${{ runner.os }}-01-dialyzer
      - name: Instal Mix and Rebar
        run: mix local.hex --force && mix local.rebar --force
      - name: Install dependencies
        run: mix deps.get
      # - name: Run Dialyzer
      #   run: mix dialyzer
      - name: Run tests
        env:
          RAVENDB_URL: "http://ravendb:8080"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mix coveralls.github
